esphome:
  name: epaper_minimal

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.129.105
    gateway: 192.168.128.1
    subnet: 255.255.254.0
    dns1: 8.8.8.8

script:
  - id: update_screen
    then:
      - component.update: eink_display

time:
  - platform: sntp
    id: sntp_time
    timezone: "Europe/Brussels"
    on_time:
      # 08:00
      - seconds: 0
        minutes: 0
        hours: 8
        then:
          - script.execute: update_screen
      # 16:00
      - seconds: 0
        minutes: 0
        hours: 16
        then:
          - script.execute: update_screen
      # 20:00
      - seconds: 0
        minutes: 0
        hours: 20
        then:
          - script.execute: update_screen
logger:

api:

ota:
  platform: esphome  # <-- nécessaire maintenant

spi:
  clk_pin: 13
  mosi_pin: 14

font:
  ######### REGULAR ############
  - file: "epaper/GothamRnd-Book.ttf"
    id: book20
    size: 20
    glyphs: &font-glyphs
      ['!', '"', '%', '(', ')', '+', '=', ',', '-', '_', '.', ':', '°', ' ', '/',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
      'é', 'à', 'è', 'ç', 'ù', 'ö', 'É', 'À', 'È', 'Ç', 'Ù']
  - file: "epaper/GothamRnd-Book.ttf"
    id: book25
    size: 25
    glyphs : *font-glyphs 
  ########## BOLD ############ 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold15
    size: 15
    glyphs : *font-glyphs 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold20
    size: 20
    glyphs : *font-glyphs 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold25
    size: 25
    glyphs : *font-glyphs 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold30
    size: 30
    glyphs : *font-glyphs 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold35
    size: 35
    glyphs : *font-glyphs 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold40
    size: 40
    glyphs : *font-glyphs 
  - file: "epaper/GothamRnd-Bold.ttf"
    id: bold55
    size: 55
    glyphs: ['.', '°', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'C', '-']

  - file: 'epaper/materialdesignicons-webfont.ttf'
    id: mdi120
    size: 120
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
      - "\U000F0A70" # mdi-silverware-fork-knife
      - "\U000F1A74" # mdi-solar-power-variant-outline
      - "\U000F1904" # mdi-home-lightning-bolt-outline
      - "\U000F0E0A" # mdi-water
      - "\U000F0A7A" # mdi-trash
      - "\U000F0A72" # mdi-solar-prod
      - "\U000F192C" # mdi-import-energy
      - "\U000F192D" # mdi-export_energie
      - "\U000F1A1B" # mdi-gas-burner
      - "\U000F140B" # mdi-energy
      - "\U000F09B8" # mdi-arrow-left
      - "\U000F09BA" # mdi-arrow-right
      - "\U000F1906" # mdi-leaf
      - "\U000F1363" # mdi-bottle-plastic
      - "\U000F03D6" # mdi-cardboard
      - "\U000F1873" # mdi-glass


  - file: 'epaper/materialdesignicons-webfont.ttf'
    id: mdi36
    size: 36
    glyphs: *mdi-weather-glyphs
  - file: 'epaper/materialdesignicons-webfont.ttf'
    id: mdi20
    size: 20
    glyphs: *mdi-weather-glyphs
    
sensor:
  - platform: homeassistant
    entity_id: weather.pont_a_celles
    attribute: temperature
    id: weather_temperature
  - platform: homeassistant
    entity_id: counter.compteur_de_vidage_du_puit
    id: compteur_vidage
  - platform: homeassistant
    entity_id: sensor.compteur_d_eau
    id: compteur_d_eau
  - platform: homeassistant
    entity_id: sensor.kiosk_fusion_solar_2025_0pi5kpb8ji7853vmxnvqzlzfkzi0qqur_total_current_day_energy
    id: prod_solaire_jour
  - platform: homeassistant
    entity_id: sensor.gazmeter_epaper_25
    id: gasmeter
  - platform: homeassistant
    entity_id: sensor.conso_generale_quotidienne_epaper_25
    id: conso_elec_quoti
  - platform: homeassistant
    entity_id: sensor.elec_epaper_25
    id: import_energie
  - platform: homeassistant
    entity_id: sensor.export_energie_epaper_25
    id: export_energie
  - platform: homeassistant
    entity_id: sensor.autoconsommation_epaper_25
    id: autoconsommation

text_sensor: 
  - platform: homeassistant
    entity_id: sensor.date
    id: date_fr_complete
  - platform: homeassistant
    entity_id: sensor.mealie_today_name
    id: plat_du_jour
  - platform: homeassistant
    entity_id: sensor.papiers_cartons
    id: carton_date
  - platform: homeassistant
    entity_id: sensor.pmc
    id: pmc_date
  - platform: homeassistant
    entity_id: sensor.verre
    id: verre_date
  - platform: homeassistant
    entity_id: sensor.dechets_organiques
    id: dechets_organiques_date
display:
  - platform: waveshare_epaper
    id: eink_display
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50inV2
    rotation: 270° #Résolution écran 480x800
    update_interval: 180s
    lambda: |-
      //Tableau des jours en français
      const char* jours_fr[] = {"Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"};
      //Récupération de la date et heure actuelle
      auto time = id(sntp_time).now();
      if (time.is_valid()) {
      // Construction de la ligne "Jour JJ-MM-AAAA"
      char buffer[40];
      snprintf(buffer, sizeof(buffer), "%s %02d-%02d-%04d",
             jours_fr[time.day_of_week % 7], // conversion jour en français
             time.day_of_month,
             time.month,
             time.year);
      // Affichage centré en haut
      it.printf(240, 15, id(bold35), TextAlign::TOP_CENTER, "%s", buffer);
      }
      //it.strftime(240, 15, id(bold35), TextAlign::TOP_CENTER, "%d-%m-%Y", id(sntp_time).now()); A supprimer
      it.filled_rectangle(50, 50, 400, 3); // ligne horizontale 
      it.printf(240, 70, id(bold20), TextAlign::TOP_CENTER, "Plat du jour :");
      it.printf(240, 95, id(book20), TextAlign::TOP_CENTER, "%s", id(plat_du_jour).state.c_str());
      it.filled_rectangle(50, 370, 380, 2);
      it.print(168, 380, id(mdi36), TextAlign::TOP_CENTER, "\U000F0A7A"); // picto poubelle
      it.printf(240, 390, id(bold20), TextAlign::TOP_CENTER, "Poubelles :");
      it.print(20, 415, id(mdi36), TextAlign::TOP_CENTER, "\U000F1906"); //picto leaf
      it.print(20, 440, id(mdi36), TextAlign::TOP_CENTER, "\U000F1363"); //picto bottle plastic
      it.print(260, 415, id(mdi36), TextAlign::TOP_CENTER, "\U000F03D6"); //picto cardboard
      it.print(260, 440, id(mdi36), TextAlign::TOP_CENTER, "\U000F1873"); //picto glass
      it.printf(50, 425, id(book20), TextAlign::TOP_LEFT, "%s", id(dechets_organiques_date).state.c_str()); //organique
      it.printf(50, 450, id(book20), TextAlign::TOP_LEFT, "%s", id(pmc_date).state.c_str()); //pmc
      it.printf(290, 425, id(book20), TextAlign::TOP_LEFT, "%s", id(carton_date).state.c_str()); //carton
      it.printf(290, 450, id(book20), TextAlign::TOP_LEFT, "%s", id(verre_date).state.c_str()); //verre
      it.filled_rectangle(50, 490, 380, 2); // ligne horizontale pour le tableau
      it.printf(50, 515, id(book20), TextAlign::TOP_LEFT, "%.1f litres", id(compteur_d_eau).state);
      it.print(20, 505, id(mdi36), TextAlign::TOP_CENTER, "\U000F0E0A"); //picto eau
      it.printf(50, 553, id(book20), TextAlign::TOP_LEFT, "%.1f m3", id(gasmeter).state);
      it.print(20, 540, id(mdi36), TextAlign::TOP_CENTER, "\U000F1A1B"); //picto gaz
      it.printf(50, 585, id(book20), TextAlign::TOP_LEFT, "%.1f kWh", id(conso_elec_quoti).state);
      it.print(20, 575, id(mdi36), TextAlign::TOP_CENTER, "\U000F140B"); //picto conso elec
      it.filled_rectangle(240, 490, 2, 100); // ligne verticale pour le tableau
      it.print(260, 505, id(mdi36), TextAlign::TOP_CENTER, "\U000F0A72"); //picto prod solaire
      it.printf(290, 515, id(book20), TextAlign::TOP_LEFT, "%.1f kWh", id(prod_solaire_jour).state);
      it.print(310, 540, id(mdi36), TextAlign::TOP_CENTER, "\U000F09B8");  //picto gauche
      it.print(340, 540, id(mdi36), TextAlign::TOP_CENTER, "\U000F09BA"); //picto droite
      it.printf(265, 590, id(book20), TextAlign::TOP_LEFT, "%.1f kWh", id(autoconsommation).state);
      it.printf(370, 590, id(book20), TextAlign::TOP_LEFT, "%.1f kWh", id(export_energie).state);
      it.printf(240, 620, id(book20), TextAlign::TOP_CENTER, "Vidage de la cave : %d", (int)id(compteur_vidage).state);
      it.printf(250, 785, id(bold15), TextAlign::TOP_RIGHT, "Infos mises à jour : ");
      it.strftime(255, 785, id(bold15), TextAlign::TOP_LEFT, "%d-%m-%Y %H:%M", id(sntp_time).now());
